Repository Tietoevry-Create/h5p-bildetema, pull requests merged in 2022-06, with the labels that each got.

#113 add routing with temp view for words
  common/utils/data.utils.ts
  h5p-bildetema/.storybook/preview.js
  h5p-bildetema/.storybook/preview.jsx
  h5p-bildetema/package-lock.json
  h5p-bildetema/package.json
  h5p-bildetema/src/components/App/App.stories.tsx
  h5p-bildetema/src/components/App/App.tsx
  h5p-bildetema/src/components/Bildetema/Bildetema.module.scss
  h5p-bildetema/src/components/Bildetema/Bildetema.stories.tsx
  h5p-bildetema/src/components/Bildetema/Bildetema.tsx
  h5p-bildetema/src/components/Header/Header.stories.tsx
  h5p-bildetema/src/components/TopicGrid/TopicGrid.module.scss
  h5p-bildetema/src/components/TopicGrid/TopicGrid.tsx
  h5p-bildetema/src/components/TopicGridElement/TopicGridElement.module.scss
  h5p-bildetema/src/components/TopicGridElement/TopicGridElement.tsx
  h5p-bildetema/src/h5p/H5PWrapper.tsx
Labels: non-functional

#133 Common styles and colors
  common/abstracts/_index.scss
  common/abstracts/_mixins.scss
  common/abstracts/_variables.scss
  h5p-bildetema-words-grid-view/src/abstracts/_mixins.scss
  h5p-bildetema-words-grid-view/src/abstracts/_variables.scss
  h5p-bildetema-words-grid-view/src/components/TopicWordsGrid/TopicWordsGrid.module.scss
  h5p-bildetema-words-grid-view/src/components/Word/Word.module.scss
  h5p-bildetema-words-grid-view/src/components/WordAudio/WordAudio.module.scss
  h5p-bildetema-words-grid-view/src/index.scss
  h5p-bildetema/src/abstracts/_index.scss
  h5p-bildetema/src/components/Bildetema/Bildetema.module.scss
  h5p-bildetema/src/components/Footer/Footer.module.scss
  h5p-bildetema/src/components/Header/Header.module.scss
  h5p-bildetema/src/components/Language/Language.module.scss
  h5p-bildetema/src/components/Toggle/Toggle.module.scss
  h5p-bildetema/src/components/TopicGrid/TopicGrid.module.scss
  h5p-bildetema/src/components/TopicGridElement/TopicGridElement.module.scss
  h5p-bildetema/src/components/TopicsList/TopicsList.module.scss
  h5p-bildetema/src/index.scss
Labels: non-functional

#134 Focus effect
  common/abstracts/_variables.scss
  h5p-bildetema/src/components/Bildetema/Bildetema.module.scss
Labels: non-functional

#143 Update breadcrumbs to use HashRouter
  h5p-bildetema/package-lock.json
  h5p-bildetema/package.json
  h5p-bildetema/src/components/Bildetema/Bildetema.tsx
  h5p-bildetema/src/components/Breadcrumbs/Breadcrumbs.stories.tsx
  h5p-bildetema/src/components/Breadcrumbs/Breadcrumbs.test.tsx
  h5p-bildetema/src/components/Breadcrumbs/Breadcrumbs.tsx
  h5p-bildetema/src/components/Icons/Icons.tsx
  h5p-bildetema/src/components/TopicGrid/TopicGrid.tsx
Labels: non-functional

#173 update breadcrumbs
  h5p-bildetema/semantics.json
  h5p-bildetema/src/components/App/App.stories.tsx
  h5p-bildetema/src/components/Bildetema/Bildetema.tsx
  h5p-bildetema/src/components/Breadcrumbs/Breadcrumbs.test.tsx
  h5p-bildetema/src/components/Breadcrumbs/Breadcrumbs.tsx
  h5p-bildetema/src/components/Header/Header.tsx
  h5p-bildetema/src/h5p/H5PWrapper.tsx
  h5p-bildetema/src/semantics.ts
  h5p-bildetema/src/types/TranslationKey.ts
Labels: non-functional

#168 topic images
  common/abstracts/_variables.scss
  common/types/types.ts
  common/utils/data.utils.ts
  h5p-bildetema/library.json
  h5p-bildetema/src/components/Bildetema/Bildetema.tsx
  h5p-bildetema/src/components/Breadcrumbs/Breadcrumbs.module.scss
  h5p-bildetema/src/components/Header/Header.module.scss
  h5p-bildetema/src/components/Header/Header.stories.tsx
  h5p-bildetema/src/components/Header/Header.tsx
  h5p-bildetema/src/components/Icons/Icons.tsx
  h5p-bildetema/src/components/TopicGrid/TopicGrid.module.scss
  h5p-bildetema/src/components/TopicGrid/TopicGrid.stories.tsx
  h5p-bildetema/src/components/TopicGrid/TopicGrid.tsx
  h5p-bildetema/src/components/TopicGridElement/TopicGridElement.module.scss
  h5p-bildetema/src/components/TopicGridElement/TopicGridElement.stories.tsx
  h5p-bildetema/src/components/TopicGridElement/TopicGridElement.tsx
  h5p-bildetema/src/components/TopicSizeButtons/TopicSizeButtons.module.scss
  h5p-bildetema/src/components/TopicSizeButtons/TopicSizeButtons.stories.tsx
  h5p-bildetema/src/components/TopicSizeButtons/TopicSizeButtons.tsx
  h5p-bildetema/src/components/TopicsList/TopicsList.tsx
  h5p-bildetema/src/components/Words/Words.tsx
  h5p-bildetema/src/h5p/H5PWrapper.tsx
  h5p-bildetema/src/library.ts
  package-lock.json
  package.json
Labels: non-functional

#192 Customise h5p-bildetema library update message
  .github/workflows/h5p_bildetema_check-library-version.yml
  h5p-bildetema/README.md
Labels: non-functional-h5p-bildetema

#230 update all packages
  h5p-bildetema-words-grid-view/package-lock.json
  h5p-bildetema-words-grid-view/package.json
  h5p-bildetema-words-theme-image/package-lock.json
  h5p-bildetema-words-theme-image/package.json
  h5p-bildetema-words-tree-view/package-lock.json
  h5p-bildetema-words-tree-view/package.json
  h5p-bildetema/package-lock.json
  h5p-bildetema/package.json
  h5p-editor-bildetema-words-topic-image/package-lock.json
  h5p-editor-bildetema-words-topic-image/package.json
  package-lock.json
  package.json
Labels: non-functional, non-functional-h5p-bildetema, non-functional-h5p-bildetema-words-grid-view

#229 footer update
  common/abstracts/_variables.scss
  h5p-bildetema/library.json
  h5p-bildetema/semantics.json
  h5p-bildetema/src/components/Footer/Footer.module.scss
  h5p-bildetema/src/components/Footer/Footer.tsx
  h5p-bildetema/src/library.ts
  h5p-bildetema/src/semantics.ts
  h5p-bildetema/src/types/TranslationKey.ts
Labels: non-functional-h5p-bildetema-words-grid-view
